# ijkl window movement
bind -r i select-pane -U
bind -r j select-pane -L
bind -r k select-pane -D
bind -r l select-pane -R

# swap pane
bind -r I swap-pane -d -t '{up-of}'
bind -r J swap-pane -d -t '{left-of}'
bind -r K swap-pane -d -t '{down-of}'
bind -r L swap-pane -d -t '{right-of}'

# Make C-b repeatable
run-shell -C "bind -r #{prefix} send-prefix"

# For convenience
bind e select-layout -E

# Visually choose panes
bind q display-panes -d 0
