# Observations:
# However, having multiple sets of keys in the same table and repeatable
# means that unrelated movements will chain into eachother which is very
# likely to be unwanted behavior. Example: bind prefix=C-b with -r, then
# moving backwards with C-b, start typing something that is NOT C-b and
# happens to be bound with -r, its binding will be fired instead of just
# typing.
# hjkl pane movement
bind -r -Tpanehjkl h "select-pane -L"
bind -r -Tpanehjkl j "select-pane -D"
bind -r -Tpanehjkl k "select-pane -U"
bind -r -Tpanehjkl l "select-pane -R"
bind -r -Tpanehjkl Enter "switch-client -Troot"
bind -r -Tpanehjkl Escape "switch-client -Troot"
bind -r h "select-pane -L; switch-client -Tpanehjkl"
bind -r j "select-pane -D; switch-client -Tpanehjkl"
bind -r k "select-pane -U; switch-client -Tpanehjkl"
bind -r l "select-pane -R; switch-client -Tpanehjkl"

# oO pane movements
bind -r o "select-pane -t '+'; switch-client -TpaneoO"
bind -r O "select-pane -t '-'; switch-client -TpaneoO"
bind -r -TpaneoO o select-pane -t '+'
bind -r -TpaneoO O select-pane -t '-'
bind -r -TpaneoO Enter "switch-client -Troot"
bind -r -TpaneoO Escape "switch-client -Troot"

# moving panes
bind -r H "swap-pane -d -t '{left-of}'; switch-client -TpaneHJKL"
bind -r J "swap-pane -d -t '{down-of}'; switch-client -TpaneHJKL"
bind -r K "swap-pane -d -t '{up-of}'; switch-client -TpaneHJKL"
bind -r L "swap-pane -d -t '{right-of}'; switch-client -TpaneHJKL"
bind -r -TpaneHJKL H swap-pane -d -t '{left-of}'
bind -r -TpaneHJKL J swap-pane -d -t '{down-of}'
bind -r -TpaneHJKL K swap-pane -d -t '{up-of}'
bind -r -TpaneHJKL L swap-pane -d -t '{right-of}'
bind -r -TpaneHJKL Enter "switch-client -Troot"
bind -r -TpaneHJKL Escape "switch-client -Troot"

# easier relative changes
bind -r n "next-window; switch-client -Twindownp"
bind -r p "previous-window; switch-client -Twindownp"
bind -r -Twindownp n next-window
bind -r -Twindownp p previous-window
bind -r -Twindownp Enter "switch-client -Troot"

# switching layouts
bind -r Space "next-layout; switch-client -TlayoutSpace"
bind -r -TlayoutSpace Space next-layout

# repeat prefix
run-shell -C "bind -r #{prefix} send-prefix"

# For convenience
bind e select-layout -E

# Extend pane selection duration
bind q display-panes -d 0

# Simple way to cancel repeating commands
bind -r Enter "switch-client -Troot"
bind -r Escape "switch-client -Troot"

# options
# Extend the repeat duration
set-option -g repeat-time 1000
# Because in the status line, ^[^[ causes tmux to crash
# so explicitly use emacs bindings for the status line.
set-option -g status-keys emacs
set-option -g mode-keys vi
set-option -g escape-time 100
